const { withFinalizedMod } = require("@expo/config-plugins");
const fs = require("node:fs");
const path = require("node:path");

/**
 * Reworks the share extension that `expo-share-intent` generates so it needs no
 * App Group.
 *
 * Apple only grants the App Group capability to paid developer accounts, and the
 * group is merely a mailbox for payloads too big for a URL. Everything we share
 * is a maps link, so the extension puts it straight into the deep link
 * (`<scheme>://share?text=…`) and the app reads it with `Linking`.
 *
 * Runs as a `finalized` mod because that is the only iOS mod that runs after
 * `expo-share-intent` has written its own files during the `xcodeproj` mod.
 */
module.exports = function withoutAppGroup(config) {
  return withFinalizedMod(config, [
    "ios",
    async (config) => {
      const { platformProjectRoot, projectName } = config.modRequest;
      const scheme = Array.isArray(config.scheme) ? config.scheme[0] : config.scheme;
      if (!scheme) {
        throw new Error("[withoutAppGroup] expo.scheme is required to open the app back");
      }

      const extensionDir = findExtensionDir(platformProjectRoot);
      if (!extensionDir) {
        throw new Error(
          "[withoutAppGroup] no ShareViewController.swift found — did expo-share-intent run?",
        );
      }

      fs.writeFileSync(
        path.join(extensionDir, "ShareViewController.swift"),
        shareViewController(scheme),
      );

      // The extension keeps an entitlements file (the target references it), but
      // an empty one: signing adds the identifiers it needs by itself.
      writeIfExists(path.join(extensionDir, "ShareExtension.entitlements"), EMPTY_ENTITLEMENTS);

      const appEntitlements = path.join(
        platformProjectRoot,
        projectName,
        `${projectName}.entitlements`,
      );
      dropAppGroup(appEntitlements);

      return config;
    },
  ]);
};

function findExtensionDir(platformProjectRoot) {
  const entries = fs.readdirSync(platformProjectRoot, { withFileTypes: true });
  for (const entry of entries) {
    if (!entry.isDirectory()) continue;
    const candidate = path.join(platformProjectRoot, entry.name);
    if (fs.existsSync(path.join(candidate, "ShareViewController.swift"))) return candidate;
  }
  return undefined;
}

function writeIfExists(filePath, contents) {
  if (fs.existsSync(filePath)) fs.writeFileSync(filePath, contents);
}

/** Strips the app group from the main app's entitlements, keeping the rest. */
function dropAppGroup(filePath) {
  if (!fs.existsSync(filePath)) return;
  const plist = fs.readFileSync(filePath, "utf8");
  const stripped = plist.replace(
    /\s*<key>com\.apple\.security\.application-groups<\/key>\s*<array>[\s\S]*?<\/array>/,
    "",
  );
  fs.writeFileSync(filePath, stripped);
}

const EMPTY_ENTITLEMENTS = `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict/>
</plist>
`;

const shareViewController = (scheme) => `import UIKit
import UniformTypeIdentifiers

/**
 * Collects whatever was shared, hands it to the host app through a deep link and
 * closes. No App Group: the payload travels inside the URL, which is enough for
 * the links maps apps produce.
 *
 * Generated by plugins/withoutAppGroup.js — edit that file, not this one.
 */
class ShareViewController: UIViewController {
  private let hostAppScheme = "${scheme}"
  private var hasStarted = false
  private var hasFinished = false

  override func viewDidLoad() {
    super.viewDidLoad()
    view.backgroundColor = .clear
  }

  /// The work starts here, not in \`viewDidLoad\`: before the view is on screen
  /// the responder chain has no \`UIApplication\` to open the host app with, and
  /// finishing early leaves the sheet stuck over the sharing app.
  override func viewDidAppear(_ animated: Bool) {
    super.viewDidAppear(animated)
    guard !hasStarted else { return }
    hasStarted = true

    // Whatever happens, never leave the user staring at a stuck sheet.
    DispatchQueue.main.asyncAfter(deadline: .now() + 5) { [weak self] in self?.finish() }
    collectSharedText()
  }

  /// Loads every attachment, keeping their order: maps apps send the place name
  /// as text and the link as a URL, and the name is worth keeping as a label.
  private func collectSharedText() {
    let attachments = (extensionContext?.inputItems as? [NSExtensionItem] ?? [])
      .compactMap { $0.attachments }
      .flatMap { $0 }

    guard !attachments.isEmpty else { return redirect(with: nil) }

    var pieces = [Int: String]()
    let lock = NSLock()
    let group = DispatchGroup()

    for (index, provider) in attachments.enumerated() {
      guard let type = readableType(of: provider) else { continue }
      group.enter()
      provider.loadItem(forTypeIdentifier: type.identifier, options: nil) { item, _ in
        if let value = Self.asText(item) {
          lock.lock()
          pieces[index] = value
          lock.unlock()
        }
        group.leave()
      }
    }

    group.notify(queue: .main) { [weak self] in
      let ordered = pieces.keys.sorted().compactMap { pieces[$0] }
      self?.redirect(with: ordered.joined(separator: "\\n"))
    }
  }

  private func readableType(of provider: NSItemProvider) -> UTType? {
    if provider.hasItemConformingToTypeIdentifier(UTType.url.identifier) { return .url }
    if provider.hasItemConformingToTypeIdentifier(UTType.plainText.identifier) { return .plainText }
    return nil
  }

  private static func asText(_ item: NSSecureCoding?) -> String? {
    if let url = item as? URL { return url.absoluteString }
    if let text = item as? String { return text }
    if let data = item as? Data { return String(data: data, encoding: .utf8) }
    return nil
  }

  private func redirect(with text: String?) {
    guard let text, !text.isEmpty,
      // Encoding everything but alphanumerics keeps the shared link's own \`?\`,
      // \`&\` and \`#\` from breaking the deep link we build around it.
      let payload = text.addingPercentEncoding(withAllowedCharacters: .alphanumerics),
      let url = URL(string: "\\(hostAppScheme)://share?text=\\(payload)")
    else {
      NSLog("[MapsConverter] nothing usable was shared")
      return finish()
    }

    openInHostApp(url)
    // Tearing the extension down in the same run loop can cancel the open.
    DispatchQueue.main.asyncAfter(deadline: .now() + 0.4) { [weak self] in self?.finish() }
  }

  /// Extensions have no \`UIApplication\`, so we walk up to the one hosting us.
  private func openInHostApp(_ url: URL) {
    var responder: UIResponder? = self
    while let current = responder {
      if let application = current as? UIApplication {
        application.open(url, options: [:], completionHandler: nil)
        return
      }
      responder = current.next
    }

    NSLog("[MapsConverter] no UIApplication in the responder chain, falling back")
    extensionContext?.open(url, completionHandler: nil)
  }

  private func finish() {
    guard !hasFinished else { return }
    hasFinished = true
    extensionContext?.completeRequest(returningItems: [], completionHandler: nil)
  }
}
`;
